/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


package org.platkmframework.inventory.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.data.domain.Page;

import java.util.List;

import org.platkmframework.inventory.domain.service.ValtabService;
import org.platkmframework.inventory.domain.vo.ValtabVO;

@RestController
@RequestMapping("/valtab")
public class ValtabController{

  @Autowired
  private ValtabService valtabService;

  @GetMapping("/criteria")
  public Page<ValtabVO> criteriaValtab(@RequestParam(defaultValue = "0", name="page") int page, 
		  @RequestParam(defaultValue = "10", name="size") int size){
       return  valtabService.criteriaValtab(page, size);
  }

  @GetMapping("/list")
  public List<ValtabVO> listValtab(){
       return  valtabService.listValtab();
  }

  @PostMapping
   public ValtabVO createValtab(@RequestBody ValtabVO  valtabVO) {
        return  valtabService.createValtab( valtabVO);
    }

    @GetMapping("/{id}")
    public ResponseEntity<ValtabVO> getValtabById(@PathVariable(name="id")  java.lang.Long valtabId) {
        return  valtabService.getValtabById(valtabId)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @PutMapping
    public ResponseEntity<ValtabVO> updateValtab(@RequestBody ValtabVO  valtab) {
        return  valtabService.updateValtab(valtab)
                .map(ResponseEntity::ok)
                .orElse(ResponseEntity.notFound().build());
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> removeValtab(@PathVariable(name="id") java.lang.Long valtabId) {
        return valtabService.removeValtab(valtabId) ?
                ResponseEntity.noContent().build() :
                ResponseEntity.notFound().build();
    }

}