 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package org.platkmframework.inventory.domain.entity; 

import jakarta.persistence.*;

@Entity
@Table(name="batch_movements") 
public class BatchMovements {

  @Id
  @GeneratedValue
  @Column(name="movement_id", nullable=false, precision=19, scale=0)
  private java.lang.Long movementId;


  @JoinColumn(table = "batches", name="batch_id")

  @Column(name="batch_id", nullable=true)
  private java.lang.Integer batchId;


  @Column(name="movement_type", nullable=false)
  private java.lang.String movementType;


  @Column(name="quantity", nullable=false)
  private java.lang.Float quantity;


  @Column(name="movement_date", nullable=true)
  private java.time.LocalDateTime movementDate;


  @JoinColumn(table = "users", name="user_id")

  @Column(name="user_id", nullable=true)
  private java.lang.Integer userId;


  @Column(name="notes", nullable=true, length=2147483647, scale=0)
  private java.lang.String notes;


  public  java.lang.Long getMovementId(){
    return this.movementId;
  }

  public  BatchMovements setMovementId (java.lang.Long movementId){
    this.movementId = movementId;
    return this;
  }

  public  java.lang.Integer getBatchId(){
    return this.batchId;
  }

  public  BatchMovements setBatchId (java.lang.Integer batchId){
    this.batchId = batchId;
    return this;
  }

  public  java.lang.String getMovementType(){
    return this.movementType;
  }

  public  BatchMovements setMovementType (java.lang.String movementType){
    this.movementType = movementType;
    return this;
  }

  public  java.lang.Float getQuantity(){
    return this.quantity;
  }

  public  BatchMovements setQuantity (java.lang.Float quantity){
    this.quantity = quantity;
    return this;
  }

  public  java.time.LocalDateTime getMovementDate(){
    return this.movementDate;
  }

  public  BatchMovements setMovementDate (java.time.LocalDateTime movementDate){
    this.movementDate = movementDate;
    return this;
  }

  public  java.lang.Integer getUserId(){
    return this.userId;
  }

  public  BatchMovements setUserId (java.lang.Integer userId){
    this.userId = userId;
    return this;
  }

  public  java.lang.String getNotes(){
    return this.notes;
  }

  public  BatchMovements setNotes (java.lang.String notes){
    this.notes = notes;
    return this;
  }


}