 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package org.platkmframework.inventory.domain.entity; 

import jakarta.persistence.*;

@Entity
@Table(name="categories") 
public class Categories {

  @Id
  @GeneratedValue
  @Column(name="category_id", nullable=false, precision=19, scale=0)
  private java.lang.Long categoryId;


  @Column(name="name", nullable=false)
  private java.lang.String name;


  @Column(name="description", nullable=true, length=2147483647, scale=0)
  private java.lang.String description;


  public  java.lang.Long getCategoryId(){
    return this.categoryId;
  }

  public  Categories setCategoryId (java.lang.Long categoryId){
    this.categoryId = categoryId;
    return this;
  }

  public  java.lang.String getName(){
    return this.name;
  }

  public  Categories setName (java.lang.String name){
    this.name = name;
    return this;
  }

  public  java.lang.String getDescription(){
    return this.description;
  }

  public  Categories setDescription (java.lang.String description){
    this.description = description;
    return this;
  }


}