 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package org.platkmframework.inventory.domain.entity; 

import jakarta.persistence.*;

@Entity
@Table(name="clients") 
public class Clients {

  @Id
  @GeneratedValue
  @Column(name="client_id", nullable=false, precision=10, scale=0)
  private java.lang.Long clientId;


  @Column(name="name", nullable=false)
  private java.lang.String name;


  @Column(name="contact", nullable=true)
  private java.lang.String contact;


  @Column(name="address", nullable=true, length=2147483647, scale=0)
  private java.lang.String address;


  @Column(name="phone", nullable=true)
  private java.lang.String phone;


  @Column(name="email", nullable=true)
  private java.lang.String email;


  public  java.lang.Long getClientId(){
    return this.clientId;
  }

  public  Clients setClientId (java.lang.Long clientId){
    this.clientId = clientId;
    return this;
  }

  public  java.lang.String getName(){
    return this.name;
  }

  public  Clients setName (java.lang.String name){
    this.name = name;
    return this;
  }

  public  java.lang.String getContact(){
    return this.contact;
  }

  public  Clients setContact (java.lang.String contact){
    this.contact = contact;
    return this;
  }

  public  java.lang.String getAddress(){
    return this.address;
  }

  public  Clients setAddress (java.lang.String address){
    this.address = address;
    return this;
  }

  public  java.lang.String getPhone(){
    return this.phone;
  }

  public  Clients setPhone (java.lang.String phone){
    this.phone = phone;
    return this;
  }

  public  java.lang.String getEmail(){
    return this.email;
  }

  public  Clients setEmail (java.lang.String email){
    this.email = email;
    return this;
  }


}