 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package org.platkmframework.inventory.domain.entity; 

import jakarta.persistence.*;

@Entity
@Table(name="products") 
public class Products {

  @Id
  @GeneratedValue
  @Column(name="product_id", nullable=false, precision=19, scale=0)
  private java.lang.Long productId;


  @Column(name="name", nullable=false)
  private java.lang.String name;


  @Column(name="description", nullable=true, length=2147483647, scale=0)
  private java.lang.String description;


  @JoinColumn(table = "categories", name="category_id")

  @Column(name="category_id", nullable=true)
  private java.lang.Integer categoryId;


  @Column(name="purchase_price", nullable=false)
  private java.lang.Float purchasePrice;


  @Column(name="sale_price", nullable=false)
  private java.lang.Float salePrice;


  @Column(name="unit", nullable=false)
  private java.lang.String unit;


  @Column(name="min_quantity", nullable=true)
  private java.lang.Float minQuantity;


  @Column(name="batch_managed", nullable=true)
  private java.lang.Boolean batchManaged;


  @Column(name="perishable", nullable=true)
  private java.lang.Boolean perishable;


  @Column(name="status", nullable=true)
  private java.lang.Boolean status;


  public  java.lang.Long getProductId(){
    return this.productId;
  }

  public  Products setProductId (java.lang.Long productId){
    this.productId = productId;
    return this;
  }

  public  java.lang.String getName(){
    return this.name;
  }

  public  Products setName (java.lang.String name){
    this.name = name;
    return this;
  }

  public  java.lang.String getDescription(){
    return this.description;
  }

  public  Products setDescription (java.lang.String description){
    this.description = description;
    return this;
  }

  public  java.lang.Integer getCategoryId(){
    return this.categoryId;
  }

  public  Products setCategoryId (java.lang.Integer categoryId){
    this.categoryId = categoryId;
    return this;
  }

  public  java.lang.Float getPurchasePrice(){
    return this.purchasePrice;
  }

  public  Products setPurchasePrice (java.lang.Float purchasePrice){
    this.purchasePrice = purchasePrice;
    return this;
  }

  public  java.lang.Float getSalePrice(){
    return this.salePrice;
  }

  public  Products setSalePrice (java.lang.Float salePrice){
    this.salePrice = salePrice;
    return this;
  }

  public  java.lang.String getUnit(){
    return this.unit;
  }

  public  Products setUnit (java.lang.String unit){
    this.unit = unit;
    return this;
  }

  public  java.lang.Float getMinQuantity(){
    return this.minQuantity;
  }

  public  Products setMinQuantity (java.lang.Float minQuantity){
    this.minQuantity = minQuantity;
    return this;
  }

  public  java.lang.Boolean getBatchManaged(){
    return this.batchManaged;
  }

  public  Products setBatchManaged (java.lang.Boolean batchManaged){
    this.batchManaged = batchManaged;
    return this;
  }

  public  java.lang.Boolean getPerishable(){
    return this.perishable;
  }

  public  Products setPerishable (java.lang.Boolean perishable){
    this.perishable = perishable;
    return this;
  }

  public  java.lang.Boolean getStatus(){
    return this.status;
  }

  public  Products setStatus (java.lang.Boolean status){
    this.status = status;
    return this;
  }


}