 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package org.platkmframework.inventory.domain.entity; 

import jakarta.persistence.*;

@Entity
@Table(name="valtab") 
public class Valtab {

  @Id
  @GeneratedValue
  @Column(name="valtab_id", nullable=false, precision=10, scale=0)
  private java.lang.Long valtabId;


  @Column(name="values", nullable=false)
  private java.lang.String values;


  @Column(name="code", nullable=false)
  private java.lang.String code;


  @Column(name="description", nullable=true, length=2147483647, scale=0)
  private java.lang.String description;


  @Column(name="default_value", nullable=true)
  private java.lang.String defaultValue;


  public  java.lang.Long getValtabId(){
    return this.valtabId;
  }

  public  Valtab setValtabId (java.lang.Long valtabId){
    this.valtabId = valtabId;
    return this;
  }

  public  java.lang.String getValues(){
    return this.values;
  }

  public  Valtab setValues (java.lang.String values){
    this.values = values;
    return this;
  }

  public  java.lang.String getCode(){
    return this.code;
  }

  public  Valtab setCode (java.lang.String code){
    this.code = code;
    return this;
  }

  public  java.lang.String getDescription(){
    return this.description;
  }

  public  Valtab setDescription (java.lang.String description){
    this.description = description;
    return this;
  }

  public  java.lang.String getDefaultValue(){
    return this.defaultValue;
  }

  public  Valtab setDefaultValue (java.lang.String defaultValue){
    this.defaultValue = defaultValue;
    return this;
  }


}