 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package  org.platkmframework.inventory.domain.dao;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.platkmframework.inventory.domain.entity.BatchMovements;

@Repository
public interface BatchMovementsRepository extends JpaRepository<BatchMovements, java.lang.Long>{
}