 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package  org.platkmframework.inventory.domain.dao;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.platkmframework.inventory.domain.entity.BatchEntries;

@Repository
public interface BatchEntriesRepository extends JpaRepository<BatchEntries, java.lang.Long>{
}