/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package  org.platkmframework.inventory.domain.dao;

import  org.platkmframework.inventory.domain.vo.CategoriesVO;
import  org.platkmframework.inventory.domain.entity.Categories;

public class CategoriesMapper{

     public static CategoriesVO toVO(Categories categories) {
        CategoriesVO vo = new CategoriesVO();
      vo.setCategoryId(categories.getCategoryId());
      vo.setName(categories.getName());
      vo.setDescription(categories.getDescription());
        return vo;
    }

    public static Categories toEntity(CategoriesVO vo) {
        Categories categories = new Categories();
       categories.setName(vo.getName());
       categories.setDescription(vo.getDescription());
        return categories;
    }

    public static Categories toEntity(CategoriesVO vo, Categories categories) {

       categories.setName(vo.getName());
       categories.setDescription(vo.getDescription());
        return categories;
    }

}