 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package  org.platkmframework.inventory.domain.dao;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.platkmframework.inventory.domain.entity.Categories;

@Repository
public interface CategoriesRepository extends JpaRepository<Categories, java.lang.Long>{
}