/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package  org.platkmframework.inventory.domain.dao;

import  org.platkmframework.inventory.domain.vo.ClientsVO;
import  org.platkmframework.inventory.domain.entity.Clients;

public class ClientsMapper{

     public static ClientsVO toVO(Clients clients) {
        ClientsVO vo = new ClientsVO();
      vo.setClientId(clients.getClientId());
      vo.setName(clients.getName());
      vo.setContact(clients.getContact());
      vo.setAddress(clients.getAddress());
      vo.setPhone(clients.getPhone());
      vo.setEmail(clients.getEmail());
        return vo;
    }

    public static Clients toEntity(ClientsVO vo) {
        Clients clients = new Clients();
       clients.setName(vo.getName());
       clients.setContact(vo.getContact());
       clients.setAddress(vo.getAddress());
       clients.setPhone(vo.getPhone());
       clients.setEmail(vo.getEmail());
        return clients;
    }

    public static Clients toEntity(ClientsVO vo, Clients clients) {

       clients.setName(vo.getName());
       clients.setContact(vo.getContact());
       clients.setAddress(vo.getAddress());
       clients.setPhone(vo.getPhone());
       clients.setEmail(vo.getEmail());
        return clients;
    }

}