/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package  org.platkmframework.inventory.domain.dao;

import  org.platkmframework.inventory.domain.vo.ProductsVO;
import  org.platkmframework.inventory.domain.entity.Products;

public class ProductsMapper{

     public static ProductsVO toVO(Products products) {
        ProductsVO vo = new ProductsVO();
      vo.setProductId(products.getProductId());
      vo.setName(products.getName());
      vo.setDescription(products.getDescription());
      vo.setCategoryId(products.getCategoryId());
      vo.setPurchasePrice(products.getPurchasePrice());
      vo.setSalePrice(products.getSalePrice());
      vo.setUnit(products.getUnit());
      vo.setMinQuantity(products.getMinQuantity());
      vo.setBatchManaged(products.getBatchManaged());
      vo.setPerishable(products.getPerishable());
      vo.setStatus(products.getStatus());
        return vo;
    }

    public static Products toEntity(ProductsVO vo) {
        Products products = new Products();
       products.setName(vo.getName());
       products.setDescription(vo.getDescription());
       products.setCategoryId(vo.getCategoryId());
       products.setPurchasePrice(vo.getPurchasePrice());
       products.setSalePrice(vo.getSalePrice());
       products.setUnit(vo.getUnit());
       products.setMinQuantity(vo.getMinQuantity());
       products.setBatchManaged(vo.getBatchManaged());
       products.setPerishable(vo.getPerishable());
       products.setStatus(vo.getStatus());
        return products;
    }

    public static Products toEntity(ProductsVO vo, Products products) {

       products.setName(vo.getName());
       products.setDescription(vo.getDescription());
       products.setCategoryId(vo.getCategoryId());
       products.setPurchasePrice(vo.getPurchasePrice());
       products.setSalePrice(vo.getSalePrice());
       products.setUnit(vo.getUnit());
       products.setMinQuantity(vo.getMinQuantity());
       products.setBatchManaged(vo.getBatchManaged());
       products.setPerishable(vo.getPerishable());
       products.setStatus(vo.getStatus());
        return products;
    }

}