 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package  org.platkmframework.inventory.domain.dao;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.platkmframework.inventory.domain.entity.Products;

@Repository
public interface ProductsRepository extends JpaRepository<Products, java.lang.Long>{
}