/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package  org.platkmframework.inventory.domain.dao;

import  org.platkmframework.inventory.domain.vo.ValtabVO;
import  org.platkmframework.inventory.domain.entity.Valtab;

public class ValtabMapper{

     public static ValtabVO toVO(Valtab valtab) {
        ValtabVO vo = new ValtabVO();
      vo.setValtabId(valtab.getValtabId());
      vo.setValues(valtab.getValues());
      vo.setCode(valtab.getCode());
      vo.setDescription(valtab.getDescription());
      vo.setDefaultValue(valtab.getDefaultValue());
        return vo;
    }

    public static Valtab toEntity(ValtabVO vo) {
        Valtab valtab = new Valtab();
       valtab.setValues(vo.getValues());
       valtab.setCode(vo.getCode());
       valtab.setDescription(vo.getDescription());
       valtab.setDefaultValue(vo.getDefaultValue());
        return valtab;
    }

    public static Valtab toEntity(ValtabVO vo, Valtab valtab) {

       valtab.setValues(vo.getValues());
       valtab.setCode(vo.getCode());
       valtab.setDescription(vo.getDescription());
       valtab.setDefaultValue(vo.getDefaultValue());
        return valtab;
    }

}