/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package org.platkmframework.inventory.domain.vo;

import java.io.Serializable;

public class BatchEntriesVO  implements Serializable{

 private static final long serialVersionUID = 1L;

private java.lang.Long entryId;

private java.lang.Integer batchId;

private java.lang.Integer productId;

private java.lang.Double quantity;

private java.time.LocalDateTime entryDate;

private java.lang.Integer supplierId;

private java.lang.Integer userId;

 
  public  java.lang.Long getEntryId(){
    return this.entryId;
  }

  public  BatchEntriesVO setEntryId (java.lang.Long entryId){
    this.entryId = entryId;
    return this;
  }

  public  java.lang.Integer getBatchId(){
    return this.batchId;
  }

  public  BatchEntriesVO setBatchId (java.lang.Integer batchId){
    this.batchId = batchId;
    return this;
  }

  public  java.lang.Integer getProductId(){
    return this.productId;
  }

  public  BatchEntriesVO setProductId (java.lang.Integer productId){
    this.productId = productId;
    return this;
  }

  public  java.lang.Double getQuantity(){
    return this.quantity;
  }

  public  BatchEntriesVO setQuantity (java.lang.Double quantity){
    this.quantity = quantity;
    return this;
  }

  public  java.time.LocalDateTime getEntryDate(){
    return this.entryDate;
  }

  public  BatchEntriesVO setEntryDate (java.time.LocalDateTime entryDate){
    this.entryDate = entryDate;
    return this;
  }

  public  java.lang.Integer getSupplierId(){
    return this.supplierId;
  }

  public  BatchEntriesVO setSupplierId (java.lang.Integer supplierId){
    this.supplierId = supplierId;
    return this;
  }

  public  java.lang.Integer getUserId(){
    return this.userId;
  }

  public  BatchEntriesVO setUserId (java.lang.Integer userId){
    this.userId = userId;
    return this;
  }




}