/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package org.platkmframework.inventory.domain.vo;

import java.io.Serializable;

public class ClientsVO  implements Serializable{

 private static final long serialVersionUID = 1L;

private java.lang.Long clientId;

private java.lang.String name;

private java.lang.String contact;

private java.lang.String address;

private java.lang.String phone;

private java.lang.String email;

 
  public  java.lang.Long getClientId(){
    return this.clientId;
  }

  public  ClientsVO setClientId (java.lang.Long clientId){
    this.clientId = clientId;
    return this;
  }

  public  java.lang.String getName(){
    return this.name;
  }

  public  ClientsVO setName (java.lang.String name){
    this.name = name;
    return this;
  }

  public  java.lang.String getContact(){
    return this.contact;
  }

  public  ClientsVO setContact (java.lang.String contact){
    this.contact = contact;
    return this;
  }

  public  java.lang.String getAddress(){
    return this.address;
  }

  public  ClientsVO setAddress (java.lang.String address){
    this.address = address;
    return this;
  }

  public  java.lang.String getPhone(){
    return this.phone;
  }

  public  ClientsVO setPhone (java.lang.String phone){
    this.phone = phone;
    return this;
  }

  public  java.lang.String getEmail(){
    return this.email;
  }

  public  ClientsVO setEmail (java.lang.String email){
    this.email = email;
    return this;
  }




}