/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/

package org.platkmframework.inventory.domain.vo;

import java.io.Serializable;

public class ValtabVO  implements Serializable{

 private static final long serialVersionUID = 1L;

private java.lang.Long valtabId;

private java.lang.String values;

private java.lang.String code;

private java.lang.String description;

private java.lang.String defaultValue;

 
  public  java.lang.Long getValtabId(){
    return this.valtabId;
  }

  public  ValtabVO setValtabId (java.lang.Long valtabId){
    this.valtabId = valtabId;
    return this;
  }

  public  java.lang.String getValues(){
    return this.values;
  }

  public  ValtabVO setValues (java.lang.String values){
    this.values = values;
    return this;
  }

  public  java.lang.String getCode(){
    return this.code;
  }

  public  ValtabVO setCode (java.lang.String code){
    this.code = code;
    return this;
  }

  public  java.lang.String getDescription(){
    return this.description;
  }

  public  ValtabVO setDescription (java.lang.String description){
    this.description = description;
    return this;
  }

  public  java.lang.String getDefaultValue(){
    return this.defaultValue;
  }

  public  ValtabVO setDefaultValue (java.lang.String defaultValue){
    this.defaultValue = defaultValue;
    return this;
  }




}