 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


package org.platkmframework.inventory.domain.service;

import org.platkmframework.inventory.domain.vo.BatchMovementsVO;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;

public interface BatchMovementsService {
  
  public List<BatchMovementsVO> listBatchMovements(); 

 public Page<BatchMovementsVO>criteriaBatchMovements(int page, int size); 

  public BatchMovementsVO createBatchMovements(BatchMovementsVO batchmovementsVO) ;

  public Optional<BatchMovementsVO> getBatchMovementsById(java.lang.Long movementId);

  public Optional<BatchMovementsVO> updateBatchMovements(BatchMovementsVO batchmovements);

  public  boolean removeBatchMovements(java.lang.Long movementId);
}