 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


package org.platkmframework.inventory.domain.service;

import org.platkmframework.inventory.domain.vo.BatchEntriesVO;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;

public interface BatchEntriesService {
  
  public List<BatchEntriesVO> listBatchEntries(); 

 public Page<BatchEntriesVO>criteriaBatchEntries(int page, int size); 

  public BatchEntriesVO createBatchEntries(BatchEntriesVO batchentriesVO) ;

  public Optional<BatchEntriesVO> getBatchEntriesById(java.lang.Long entryId);

  public Optional<BatchEntriesVO> updateBatchEntries(BatchEntriesVO batchentries);

  public  boolean removeBatchEntries(java.lang.Long entryId);
}