 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


package org.platkmframework.inventory.domain.service;

import org.platkmframework.inventory.domain.vo.ClientsVO;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;

public interface ClientsService {
  
  public List<ClientsVO> listClients(); 

 public Page<ClientsVO>criteriaClients(int page, int size); 

  public ClientsVO createClients(ClientsVO clientsVO) ;

  public Optional<ClientsVO> getClientsById(java.lang.Long clientId);

  public Optional<ClientsVO> updateClients(ClientsVO clients);

  public  boolean removeClients(java.lang.Long clientId);
}