 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


package org.platkmframework.inventory.domain.service;

import org.platkmframework.inventory.domain.vo.ProductsVO;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;

public interface ProductsService {
  
  public List<ProductsVO> listProducts(); 

 public Page<ProductsVO>criteriaProducts(int page, int size); 

  public ProductsVO createProducts(ProductsVO productsVO) ;

  public Optional<ProductsVO> getProductsById(java.lang.Long productId);

  public Optional<ProductsVO> updateProducts(ProductsVO products);

  public  boolean removeProducts(java.lang.Long productId);
}