 /*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/


package org.platkmframework.inventory.domain.service;

import org.platkmframework.inventory.domain.vo.ValtabVO;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;

public interface ValtabService {
  
  public List<ValtabVO> listValtab(); 

 public Page<ValtabVO>criteriaValtab(int page, int size); 

  public ValtabVO createValtab(ValtabVO valtabVO) ;

  public Optional<ValtabVO> getValtabById(java.lang.Long valtabId);

  public Optional<ValtabVO> updateValtab(ValtabVO valtab);

  public  boolean removeValtab(java.lang.Long valtabId);
}